[project]
name = "hybridflowshop"
version = "0.0.1"
description = "Hybrid Flow Shop Scheduling Problem"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "mbls",
    "openpyxl>=3.1.5",
    "ortools>=9.12.4544",
    "pandas>=2.3.0",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
    "routix",
    "schore==0.0.4",
]

[dependency-groups]
dev = [
    "pandas-stubs>=2.3.0.250703",
    "pip>=25.1.1",
    "types-pyyaml>=6.0.12.20250516",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
pythonpath = ["."]

[tool.uv.sources]
mbls = { path = "../mbls", editable = true }
routix = { path = "../routix", editable = true }
