[project]
name = "hybridflowshop"
version = "0.0.1"
description = "Hybrid Flow Shop Scheduling Problem"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "mbls",
    "ortools==9.14.6206",
    "pandas>=2.3.0",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
    "routix",
    "schore",
    "xlsxwriter>=3.2.5",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pandas-stubs>=2.3.0.250703",
    "pip>=25.1.1",
    "pytest>=9.0.2",
    "ruff>=0.15.2",
    "ty>=0.0.17",
    "types-openpyxl>=3.1.5.20250602",
    "types-pyyaml>=6.0.12.20250516",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
pythonpath = ["."]

[project.scripts]
exp_compare = "exp_compare.main_cli:main"

[tool.uv.sources]
mbls = { path = "../mbls", editable = true }
routix = { path = "../routix", editable = true }
schore = { path = "../schore", editable = true }
