input_dir: resources/ff2020big
baseline_csv_path: resources/ff2020big_ref/fan2023.csv
benchmark_idx_start: 1
benchmark_idx_end: 240
seed_count: 10
output_dir: Outputs_paper_fan2023
draw_convergence: true
random_seed_base: 1
scenario: fan2023_hea
time_limit_scale: 1.0
